name: greismorr_web
description: Greismorr online portfolio.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.6
  flutter_i18n: ^0.36.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.7
  flutter_circular_text: "^0.3.1"
  provider: ^6.1.1
  url_launcher: ^6.2.1

dependency_overrides:
  archive: ^3.6.1
  win32: ^5.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutterando_analysis: ^0.0.2
  flutter_lints: ^2.0.0

flutter_native_splash:
  android: false
  ios: false
  color: "#000000"
  web_image_mode: center
  image: assets/splash/splash.gif

flutter:
  uses-material-design: true

  assets:
    - assets/splash/
    - assets/i18n/
    - assets/icons/
    - assets/images/
    - assets/images/mesh_gradient/
    - assets/images/about/
    - assets/images/projects/
    - assets/images/technologies/
